/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Databasechangeloglock;
import jooq.tables.ProfileChange;
import jooq.tables.ProfileHistory;
import jooq.tables.records.DatabasechangeloglockRecord;
import jooq.tables.records.ProfileChangeRecord;
import jooq.tables.records.ProfileHistoryRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * profile.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), new TableField[]{Databasechangeloglock.DATABASECHANGELOGLOCK.ID}, true);
    public static final UniqueKey<ProfileChangeRecord> PROFILE_CHANGE_PKEY = Internal.createUniqueKey(ProfileChange.PROFILE_CHANGE, DSL.name("profile_change_pkey"), new TableField[]{ProfileChange.PROFILE_CHANGE.ID}, true);
    public static final UniqueKey<ProfileHistoryRecord> PROFILE_HISTORY_PK = Internal.createUniqueKey(ProfileHistory.PROFILE_HISTORY, DSL.name("profile_history_pk"), new TableField[]{ProfileHistory.PROFILE_HISTORY.PROFILE}, true);
}
