/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Databasechangelog;
import jooq.tables.Databasechangeloglock;
import jooq.tables.ProfileChange;
import jooq.tables.ProfileHistory;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Profile extends SchemaImpl {

    /**
     * The reference instance of <code>profile</code>
     */
    public static final Profile PROFILE = new Profile();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>profile.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>profile.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>profile.profile_change</code>.
     */
    public final ProfileChange PROFILE_CHANGE = ProfileChange.PROFILE_CHANGE;

    /**
     * The table <code>profile.profile_history</code>.
     */
    public final ProfileHistory PROFILE_HISTORY = ProfileHistory.PROFILE_HISTORY;

    /**
     * No further instances allowed
     */
    private Profile() {
        super("profile", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
                Databasechangelog.DATABASECHANGELOG,
                Databasechangeloglock.DATABASECHANGELOGLOCK,
                ProfileChange.PROFILE_CHANGE,
                ProfileHistory.PROFILE_HISTORY
        );
    }
}
