/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Databasechangelog;
import jooq.tables.Databasechangeloglock;
import jooq.tables.ProfileChange;
import jooq.tables.ProfileHistory;


/**
 * Convenience access to all tables in profile.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>profile.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>profile.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>profile.profile_change</code>.
     */
    public static final ProfileChange PROFILE_CHANGE = ProfileChange.PROFILE_CHANGE;

    /**
     * The table <code>profile.profile_history</code>.
     */
    public static final ProfileHistory PROFILE_HISTORY = ProfileHistory.PROFILE_HISTORY;
}
