/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.ProfileChange;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProfileChangeRecord extends UpdatableRecordImpl<ProfileChangeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached ProfileChangeRecord
     */
    public ProfileChangeRecord() {
        super(ProfileChange.PROFILE_CHANGE);
    }

    /**
     * Create a detached, initialised ProfileChangeRecord
     */
    public ProfileChangeRecord(Long id, String parentId, String masterProfile, Long masterProfileVersion, String deactivatedProfileMerge, Long deactivatedProfileMergeVersion, String deactivatedProfileUnmerge, Long deactivatedProfileUnmergeVersion, String newProfile, String activatedProfile, Long activatedProfileVersion, String operationType, LocalDateTime createDate) {
        super(ProfileChange.PROFILE_CHANGE);

        setId(id);
        setParentId(parentId);
        setMasterProfile(masterProfile);
        setMasterProfileVersion(masterProfileVersion);
        setDeactivatedProfileMerge(deactivatedProfileMerge);
        setDeactivatedProfileMergeVersion(deactivatedProfileMergeVersion);
        setDeactivatedProfileUnmerge(deactivatedProfileUnmerge);
        setDeactivatedProfileUnmergeVersion(deactivatedProfileUnmergeVersion);
        setNewProfile(newProfile);
        setActivatedProfile(activatedProfile);
        setActivatedProfileVersion(activatedProfileVersion);
        setOperationType(operationType);
        setCreateDate(createDate);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>profile.profile_change.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>profile.profile_change.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>profile.profile_change.parent_id</code>.
     */
    public String getParentId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>profile.profile_change.parent_id</code>.
     */
    public void setParentId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>profile.profile_change.master_profile</code>.
     */
    public String getMasterProfile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>profile.profile_change.master_profile</code>.
     */
    public void setMasterProfile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>profile.profile_change.master_profile_version</code>.
     */
    public Long getMasterProfileVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>profile.profile_change.master_profile_version</code>.
     */
    public void setMasterProfileVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>profile.profile_change.deactivated_profile_merge</code>.
     */
    public String getDeactivatedProfileMerge() {
        return (String) get(4);
    }

    /**
     * Setter for <code>profile.profile_change.deactivated_profile_merge</code>.
     */
    public void setDeactivatedProfileMerge(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>profile.profile_change.deactivated_profile_merge_version</code>.
     */
    public Long getDeactivatedProfileMergeVersion() {
        return (Long) get(5);
    }

    /**
     * Setter for
     * <code>profile.profile_change.deactivated_profile_merge_version</code>.
     */
    public void setDeactivatedProfileMergeVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>profile.profile_change.deactivated_profile_unmerge</code>.
     */
    public String getDeactivatedProfileUnmerge() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>profile.profile_change.deactivated_profile_unmerge</code>.
     */
    public void setDeactivatedProfileUnmerge(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>profile.profile_change.deactivated_profile_unmerge_version</code>.
     */
    public Long getDeactivatedProfileUnmergeVersion() {
        return (Long) get(7);
    }

    /**
     * Setter for
     * <code>profile.profile_change.deactivated_profile_unmerge_version</code>.
     */
    public void setDeactivatedProfileUnmergeVersion(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>profile.profile_change.new_profile</code>.
     */
    public String getNewProfile() {
        return (String) get(8);
    }

    /**
     * Setter for <code>profile.profile_change.new_profile</code>.
     */
    public void setNewProfile(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>profile.profile_change.activated_profile</code>.
     */
    public String getActivatedProfile() {
        return (String) get(9);
    }

    /**
     * Setter for <code>profile.profile_change.activated_profile</code>.
     */
    public void setActivatedProfile(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>profile.profile_change.activated_profile_version</code>.
     */
    public Long getActivatedProfileVersion() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>profile.profile_change.activated_profile_version</code>.
     */
    public void setActivatedProfileVersion(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>profile.profile_change.operation_type</code>.
     */
    public String getOperationType() {
        return (String) get(11);
    }

    /**
     * Setter for <code>profile.profile_change.operation_type</code>.
     */
    public void setOperationType(String value) {
        set(11, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>profile.profile_change.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>profile.profile_change.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(12, value);
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }
}
