/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.ProfileHistory;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProfileHistoryRecord extends UpdatableRecordImpl<ProfileHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached ProfileHistoryRecord
     */
    public ProfileHistoryRecord() {
        super(ProfileHistory.PROFILE_HISTORY);
    }

    /**
     * Create a detached, initialised ProfileHistoryRecord
     */
    public ProfileHistoryRecord(String profile, Long profileVersion, Boolean isActive, String parentProfile, LocalDateTime updateDate) {
        super(ProfileHistory.PROFILE_HISTORY);

        setProfile(profile);
        setProfileVersion(profileVersion);
        setIsActive(isActive);
        setParentProfile(parentProfile);
        setUpdateDate(updateDate);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>profile.profile_history.profile</code>.
     */
    public String getProfile() {
        return (String) get(0);
    }

    /**
     * Setter for <code>profile.profile_history.profile</code>.
     */
    public void setProfile(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>profile.profile_history.profile_version</code>.
     */
    public Long getProfileVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>profile.profile_history.profile_version</code>.
     */
    public void setProfileVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>profile.profile_history.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>profile.profile_history.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>profile.profile_history.parent_profile</code>.
     */
    public String getParentProfile() {
        return (String) get(3);
    }

    /**
     * Setter for <code>profile.profile_history.parent_profile</code>.
     */
    public void setParentProfile(String value) {
        set(3, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>profile.profile_history.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>profile.profile_history.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(4, value);
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }
}
